### ISSUE TITLE
Waveform doesn't show up

### ISSUE THREAD

**Issue by HikuHatsune** [crash5band/MikuMikuWorld#49] opened 2023-11-21 14:16 UTC
![image](https://github.com/crash5band/MikuMikuWorld/assets/151648906/a49f1e0a-34de-4b54-805b-b772b0424bde)
I tried redownloading 3 times and the waveform still doesn't show up.

**Comment by HikuHatsune** [comment] 2023-11-21 14:22
Also is there anyway i can make the chart goes slower ? Like x0,5 because it goes so fast and i want to make sure that i place to notes correctly

**Comment by crash5band** [comment] 2023-11-21 14:48
Can you send me the audio file?
And no, there isn't a way to control playback speed at the moment

**Comment by HikuHatsune** [comment] 2023-11-21 14:58
ANU.mp3
<https://drive.google.com/file/d/19JnG_Y04OLmMmh2tEgHaKbly_O8ZG2uG/view?usp=drive_web>
Send this again because the file was too large to be sent


Vào Th 3, 21 thg 11, 2023 vào lúc 21:48 Sherif ***@***.***>
đã viết:

**Comment by HikuHatsune** [comment] 2023-11-21 16:14
Mine doesn't show up, no matter what audio i use

**Comment by YumYummity** [comment] 2023-12-15 20:52
Same issue here:
![image](https://github.com/crash5band/MikuMikuWorld/assets/103061664/323023f7-1acf-46f7-8928-5a72b4394bae)

**Comment by crash5band** [comment] 2023-12-31 17:06
[mmw_debug.zip](https://github.com/crash5band/MikuMikuWorld/files/13801758/mmw_debug.zip)
Still not quite sure why it isn't showing up... Can you try this build and tell me what is showing up under Audio > Waveform in the debug window?

**Comment by YumYummity** [comment] 2023-12-31 18:39
Here:
![image](https://github.com/crash5band/MikuMikuWorld/assets/103061664/2488b54c-9da6-474c-8205-05178652d9de)

**Comment by crash5band** [comment] 2023-12-31 19:04
So I managed to reproduce it by switching to integrated graphics which I'm guessing is the case for you both. In any case I managed to identify the cause and will release a fix soon

**Comment by crash5band** [comment] 2023-12-31 19:15
Fixed with beb6cb1

**Closed by crash5band** 2023-12-31 19:15 UTC

**Comment by YumYummity** [comment] 2023-12-31 20:00
Thanks!
Do you think you can provide a build of this fix (or build instructions)?

**Comment by crash5band** [comment] 2023-12-31 20:09
I'll leave the release for when I complete #50 but if you want to build it yourself I'm pretty sure building the solution with VS2022 is all that is needed.
